language: node_js
node_js: node
cache: npm

branches:
  only:
    - master

git:
  quiet: true
  submodules: false

script:
  - sed -i -e "s/00000000/$TRAVIS_BUILD_NUMBER/g" react-singleton-hook/package.json
  - (cd react-singleton-hook; ../.travis/check_changed.sh && echo "react-singleton-hook changed, building NPM package" && npm test && npm build)

deploy:
  provider: npm
  email: $EMAIL_ADDRESS
  api_key: $NPM_ACCESS_TOKEN
  skip_cleanup: true
  on:
    branch: master
    condition:  $(cd react-singleton-hook;  ../.travis/check_changed.sh; echo $?) -eq 0
